"""Initial migration

Revision ID: 4ed1393c0e75
Revises: 
Create Date: 2025-06-13 13:04:15.925866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed1393c0e75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('frame_data', sa.LargeBinary(), nullable=True),
    sa.Column('frame_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frames_id'), 'frames', ['id'], unique=False)
    op.create_index(op.f('ix_frames_sequence_number'), 'frames', ['sequence_number'], unique=False)
    op.create_index(op.f('ix_frames_timestamp'), 'frames', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_frames_timestamp'), table_name='frames')
    op.drop_index(op.f('ix_frames_sequence_number'), table_name='frames')
    op.drop_index(op.f('ix_frames_id'), table_name='frames')
    op.drop_table('frames')
    # ### end Alembic commands ### 